### ISSUE TITLE
Week 1 - Core Idea, Initial Research, and Environment Set Up

### ISSUE THREAD

**Issue by farzaa** [TeamMoodGitHub/Noah-Term-1#1]
_Universities_ have a TON of events every week and it can be tough to actually figure out whats going on and when. Facebook Events has helped a ton with this, but we still have the problem where you need to subscribed to a bunch of pages and groups to actually figure out whats going on.

This web app would aggregate all the events from all these pages (using a cron job) to get them all in one place in a nicely formatted way. This way, at a glance you can see whats going on at your university. 

During this week, Noah will begin the research phase where he will figure out things like:

- backend library choice and reasoning behind choice 
- front end library choice and reasoning behind choice 
- database choice and reasoning behind choice 
- begin researching server-less computing and cron jobs.

Other then researching, Noah will begin creating some really basic scripts that do things like pull events from the Facebook API and try and see if everything is possible and if there will be any bumps in the road. The main point of this week is to predict nay problem we may encounter.

While doing this, Noah will also spend time this week setting up his environment based on the technologies he chose from the research phase. 

Lastly, it will be worth it list out the basic features an MVP should have by the end of Term 1, this is something I will work with Noah on.

## Tasks
- [x] Research backend libraries
- [x] Research frontend libraries
- [x] Research databases 
- [x] Research server-less computing and cron jobs
- [x] Research Facebook Graph API
- [x] Set up development environment
- [x] Write scripts to pull events from Facebook API

**Comment by slokomisu** [comment]
This is where I will put the results of my research
